import Head from "next/head";
import HomeVideo from "../components/HomeVideo/HomeVideo";
import OurDevelopment from "../components/OurDevelopment/OurDevelopment";
import Trending from "../components/Trending/Trending";
import WhoWeAre from "../components/WhoWeAre/WhoWeAre";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";

import { Navigation, Pagination } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import LeadingGallery from "../components/LeadingGallery/LeadingGallery";

export default function Home() {
  
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <HomeVideo /> */}
      {/* <OurDevelopment /> */}
      {/* <Trending /> */}
      {/* <LeadingGallery /> */}
      {/* <WhoWeAre /> */}
     
        {/* <Homes /> */}
    </div>
  );
}
